import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
Employment = pd.read_csv('AusEmployment.csv', skiprows=range(1, 10))
Employment['Date'] = pd.to_datetime(Employment['Date'], format='%b-%Y')
Employment.set_index('Date', inplace=True) 
print("Cleaned Employment Data:")
print(Employment.head())
Employment = Employment.reset_index() 
Employment['Date'] = Employment['Date'] + pd.offsets.MonthEnd(0) 
print(Employment.head())
Power = pd.read_csv('DemandDataPower.csv') 
Power['Date'] = pd.to_datetime(Power['Date']) 
Power.set_index('Date', inplace=True)
Power_monthly = Power.resample('M').mean().reset_index()
comparison = pd.merge(Power_monthly, Employment, on='Date')
comparison.to_csv('PopulationTest.csv', index=False)
plt.figure(figsize=(10, 6))
plt.scatter(comparison['Employment New South Wales (000)'], comparison['Demand'], color='purple')
plt.title('Scatter Plot: Power vs Employment')
plt.xlabel('Employment (New South Wales)(Millions)')
plt.ylabel('Power Demand (Units)')
plt.grid(True)
plt.show()